# **Problem Statement**:
Edureka has hired 1000 new employees, the HR has contacted you, and provided you with a text file having new employees’ names. He wants you to help him with generating Employees IDs, Emails, and Password

# ***Tasks to be performed:***

1. Hey buddy, we have hired 1000 new employees. Here are the names in a text file, each name is separated using a new line. Can you generate the following:

 > 1.a Employee ID: Starting from 2020001. Example 2020001, 2020002 and so on

 > 1.b Email ID: first_name.last_name@edureka.co

 >1.c Password: It should be an alphanumeric value, must having capital letters, small letters, and special symbols

2. I need you to perform some operations on the data, so can we load the data in a Pandas DataFrame

3. Just to cross-check, can you show me the first 2 and the last 3 rows. Also, let’s check the shape of the DataFrame and print the data-types of each column

4. Print the employee id, email id, and password of ‘Nancy Zediker’

5. Can we check if:

>    5.a the column ‘Email ID’

>    5.b it should not contain any duplicate emails

>    5.c check its size and print the first 10 values

>  5.d If duplicate email is found, add a number in the duplicated email We     have planned to invite them on lunch in batches.

6. Lets create the first batch of all people whose names are starting with ‘A’. Also give me their count

7. I just got to know, that the people at index 10, 130, and 560 will not be joining so please remove their record

8. We also need to share the data with the finance department so can you create a new DataFrame without the password column and save it in an excel file for sharing

9. Can you tell me how I will access the data from excel file using names. For example show me the data for 'John Brown’ and 'Michael Combes’

# ***Task 1.*** 

 > 1.a Load the data-set in notebook. Each name is separated using a new line.

 > 1.b Create Employee ID: Starting from 2020001. Example 2020001, 2020002 and so on for 1000 employee.

 > 1.c Email ID: first_name.last_name@edureka.co.

 >1.d Password: It should be an alphanumeric value, must having capital letters, small letters, and special symbols.

In [1]:
#---Importing required libraries---#
import pandas as pd
import numpy as np
import random

In [2]:
import urllib.request

file = "https://www.dropbox.com/s/onl5ac2ea3v11aw/names.txt?dl=1"

urllib.request.urlretrieve(file, "names.txt")

print("Dataset downloaded successfully!")

Dataset downloaded successfully!

In [3]:
from os import read, write, remove
files = open('names.txt', 'r')
names = files.read()
files.close()

In [4]:
#---Read the names from the dataset---#
print(names)

Edward Davis
John Brown
Cristopher Mccrate
Michael Combes
Jeff Blount
Joseph Ferris
Pablo Bruner
Ronnie Waite
Edward Gonzalez
Ruby Musetti
Della Janek
Brian Main
Jennifer Fowler
Patricia Lenis
Dominique Connor
David Adkins
Helen Phelps
John Thornton
Marcos Romero
Cindy Hayes
Mellisa Huff
Frank Prater
In White
Alfredo Yu
Susan Adkins
Mandy Oehler
Sabrina Helman
Danielle Armstrong
Peter Jones
Susan Draughn
Ernest Kochanski
Doug Rinaldi
Judy Purdy
Larry Smith
Sarah Garrow
Dominque Williams
Derrick Miller
Janet Hawkes
Judy Motley
Frances Avellino
Vernon Byrd
Richard Misfeldt
Ted Olson
Martha Hamelin
Donna Markowski
Brandon Wright
Violet Volz
Rodney Simmons
Shannon Moore
Helen Floyd
Dawne Ghaemmaghami
Carlos Savage
Steven Kipling
Meghan Smith
Ryan Harding
Mabel Clark
Randall Lynn
Samantha King
Leona Fultz
Norma Stanely
Sandra Woods
Claudia Boggs
John Oliva
Laurie Whit
Michael Pike
Virgie Baptiste
Jorge Kinsinger
Shari Levine
Ashley Nettles
James Frezzo
Jana Brown
Fausto Gray
Brian Lockhart
Michelle Groh
Patsy Holmes
Kathleen Roberts
Sara Shannon
Alice Vallee
Robert Gaylor
Michael Pratka
Lara Double
Mathew Ramos
Guy Teasley
Brianna Jacobs
Roberta Clements
Royce Junkin
Ronald Shumway
Jason Sneed
David Rayburn
Elma Glenn
James Sills
Louise Farmer
Evelyn Reed
Brian Lemke
Elsie Ponce
Robert Hines
Adrienne Huber
Karen Salas
Linda Terry
Susan Esperon
Samuel Jones
William Smith
James Jones
Scottie Walker
Loretta Mcdevitt
Robert Kramer
Mirna Bush
Irvin Steinberg
Jessica Veilleux
Kristi Munson
Doris Toft
Xavier Hutchinson
Thomas Dealba
Ahmad Olson
Taylor Cendejas
Michael Anderson
Peggy Zanola
Andrew Lund
Keith Shepard
Robert Harris
Claud Rice
Angeline Roberts
Cary Levy
Lashonda Fields
Dawn Oneill
Judith Toki
Elizabeth Franks
John Heyde
Walter Mcneill
Sue Mendoza
William Ponyah
George Stark
Patrick Oconnor
Michael Hopkins
Cynthia Boyett
Pauline Duncan
Maria Banks
Kelly Pawlak
Katherine Young
Jodi Boatwright
Jeramy Sanchez
Carl Shouse
Rickey Allen
Vincent Larson
Charles Cruz
Timothy Packard
Frederick Azim
Dale Wakham
Matthew Hartman
Ashley Curtis
Emma Pearson
Erin Myers
Patricia Greaves
June Hicks
Sue Hermans
Rebecca Geier
Shirley Himes
Harriett Anderson
Letitia Turner
Mark Davine
Elmer Boos
Helen Burgess
Kathy Mallett
James Bingle
Johnnie Bass
Randall Shiver
Patricia Quince
Tom Guzman
John Gregg
Donna Robertson
Jaime Biggs
David Ragland
Vincent Matt
Jackie Gillespie
Frank Stephenson
Albert Lyons
Rachel Pettway
Tamiko Austin
Beverly Marsh
Dan Elam
Sheila Peck
Cheryl Dibble
Lee Tate
Regina Davis
Charles Blackwell
Susan Demaray
Jeffery Smith
Kenneth Valdivia
Courtney Jaynes
Keith Council
Lois Davis
Mary Dupuis
Carlos Posey
Alex Swank
Kyle Nicely
Jill Swanson
Patricia Johnstone
Samuel Santana
Gilda Stewart
Richard Smith
Charles Brendel
Blake Dube
Barbara Weddle
Michael Foley
John Hall
Billy Baker
Ola Britton
Alyssa Walker
Alex Kane
Allan Wimberly
Melvin Legault
Florence Drummond
Lino Delacruz
Ruby Reilly
Matthew Markey
Joann Ruch
Ann Houston
Donnie Stewart
Henrietta Godoy
Jason Mason
Danny Baker
James Branch
Gabriel Rhea
Timothy Tobar
Julia Gonzalez
Jc Hancock
Rosalie Picard
Marilynn Taylor
Patrick Garcia
Maria Noboa
Annie Gray
Lisa Pham
Sandra Jones
Gerald Edwards
Helen Hofmann
Dann Williams
Charles Ennis
Dwayne George
Darlene Hopper
Debbie Mercer
Mark Wood
James Jimenez
Christine Hooker
Clara Cole
Douglas Crichton
Karen Horton
Joseph Mutch
Burl Arevalo
Robert Smith
Mark Harrison
Sonya Best
Adrian Warren
David Davidson
Sondra Rodriguez
Richard Pezzuti
Bruce Jenkins
Michael Downs
Mary Brewster
Joan Taylor
James Niebaum
Diane Reeder
Nancy Cooper
John Bennet
Robert Myers
Danny James
Nancy Clay
Dennis Wurzbacher
Dale Furtado
Vernon Keiser
Michael Sparks
Jasmine Wilkinson
Judy Jones
Matthew Erdmann
Kevin Freeman
Brandon Martinez
William Lay
Everett Masterson
Eula Duncan
Sheldon Tyson
Melvin Glisson
Joan Stansel
Chelsea Galliher
Samuel Plante
Dennis Dearborn
Chester Ruth
Thomas Stevens
Francine Marak
Jane Mauro
Gary Williams
Justin Baker
Deborah Patterson
Connie Fields
Francis Matthews
Brandon Santana
Mallory Delisa
Linda Wimberly
Socorro Gainer
Raquel Davis
Lena Sanders
Robert Simonetti
James Rucker
James Caldwell
Sandra Robinson
Roberto Buddenhagen
Christopher Bean
Brett Mead
Jonathan Wilson
Penny Alderman
Edward Walley
Timothy Rowell
Aaron Huffstetler
Karen Matthews
Rose Hennessey
Donald Jones
Barbara Horan
Clyde Powell
Barry Barber
Damon Marr
Robert Jones
Maria Celadon
Robert Christ
Joseph Gramc
Dorothy Simpson
Doris Plotts
Donte Hinds
Becky Weber
Charles Dittmer
Humberto Morales
Susan Chalender
Roger Garcia
James Burt
Mason Christensen
Gary Loyd
Teresa Rodriguez
Juana Serrano
Theodore Baillargeon
Leslie Ross
Angela Criddle
Theodore Gray
Cindy Dean
Chester Stewart
Veronica Gibson
Keith Goin
Kyle Johann
Maria Andrews
Tyler Tavares
Mary Vega
Chadwick Duncan
Edward Coil
Bradley Davis
Tammy Berry
Travis Lemke
Shannon Smith
George Blalock
Raymond Link
Steven Felix
Jonathon Cutler
Kevin Avery
John Jodoin
Elaine Renn
Elizabeth Sims
Margie Joyner
Cyril Tedeschi
Derek Sundt
Patricia Schultz
Francisco Gilman
David Dombrowski
Stanley Lund
Tom Bradley
Thomas Shierling
Beth Minichiello
Alton Dates
Julie Mattie
Robert Kyer
Jackie Jones
Valerie Page
Brittany Melito
Louise Minton
Alfred Olivares
David Martinez
William Mccune
John Kanahele
Edward Edwards
Rudy Perez
Hector Babena
Dale Gipson
Jason Kleck
Blanca Evans
Richard Williams
Camille Ausmus
Tom Hammack
Anna Lievano
Douglas Echols
Iris Williams
Jill Henry
Michael Sanmiguel
Nicole Haskell
Lucy Larson
Paul Gustovich
Karen Coutts
Marlene Basinski
Michael May
Melaine Lewis
Georgette Turner
Edward Mccard
Melinda Fikes
Emily Brinton
Marion Dyckman
Lisa Dudas
Robby Jagers
Lance Townley
Henry Conrad
Tracey Ross
Chance Scott
Patricia Vannest
Kathryn Whitson
Deanna Benshoof
Clinton Payton
Huong Austin
Danielle Mcgowan
Armando Harr
Amy Weatherby
Troy Kaywood
Brenda Orozco
Donald Oliver
Matthew Mccullough
Marie Seabron
Emily West
Miriam King
William Humphrys
Shelly Lambert
Lee Goodyear
Amy Conway
Louis Zimmerman
Robin Harris
James Askew
Olga Clark
James Disher
Nancy Mallen
Barbara Dotson
Lucille Harvey
Melanie Price
Bernard Spiller
Martha Beauford
Lori Rase
Keith Barajas
William Owens
Wilbur Klein
Henry Emerson
Kimberly Alfaro
Michael Hollins
Thomas Brantly
Kathleen Hackney
Margaret Benedict
Alida Ristau
Louella Shepard
Maria Mardis
Cary Gariepy
Dana Simpson
David Rahman
Ralph Clark
Robin Walker
Beatrice Crockett
Paul Higgins
Cecilia Lemon
Robert Allen
Bertie Moore
Erika Sheffield
Pamela Williams
Charles Surbaugh
Ann Goldenberg
Steven Olson
Rudy Black
Martha Brooks
Colin Mccullen
Lois Wester
Ronald Gavin
Michael Rivera
Mary Smith
Jamie Hernandez
Jed Peters
Lashay Tipton
John House
Kenneth Heiskell
William Mclaughlin
Larry Cogswell
Carla Adame
Paulette Thompson
Stephen Place
Alfredo Diaz
Lisa Metcalf
Martha Apodaca
Allison Perry
Cynthia Meyers
Malia Skelley
Jerry Martin
Evelyn Felt
Victor Lieder
Camille Alexander
Trevor Combass
Chris Johnston
Salvador Craze
Phillis Walp
Heather Lawrence
Marcell Helton
Donald Gipson
Andrew Floyd
Matthew Richman
Mary Silvernail
Manie Ackley
Anibal Shaw
Ethel Smith
James Garcia
Sam Garrison
Irene Milliner
Edward Nathanson
Judith Mccarty
Denise Kilcoyne
Dorothy Martin
Glen Dziedzic
Dale Hays
Albert Lane
Agustin Powell
Michelle Roule
James Tolman
Dolores Roberts
Candis Eison
Dorothy Servant
Oscar Batten
April Lang
Emma Bouton
Tammy Jewett
Linda Jamison
Stephanie Durant
Patricia Pegues
Charles Rodriguez
Nicole Esparza
Gwen Shaw
Jeremiah Parks
Jessica Bell
Charles Lim
Billy Nash
Nola Jennings
Byron Genao
Mario Norman
Andrew Asmussen
Norma Gazitano
Patsy Mancini
Mary Meckes
Richard Homma
Lucille Coffey
Frank Yarbrough
Bridget Sawyer
Antionette Farnam
Kathryn Clarkson
Carl Patterson
Diane Kreidel
Tasha Perry
Terry Evans
Connie Shepherd
Joseph Brussel
James Hansing
Walter Kowalski
Richard White
Simone Roush
Nicole Baker
Maria Brown
John Schmidt
Michelle Bright
Alyssa Carpenter
Jill Rodriquez
Ronald Decker
Mary Lockett
Francisco Bueti
Florence Holman
Doris Thor
Tyler Hall
Barbara Henry
Allan Geimer
Elmer Swendsen
Robert Mazon
Denise Guzman
Russell Reper
Douglas Andrews
Hugh Archibald
Nora Costley
Dorothy Hernandez
Lauren Ross
Blake Staelens
Amy Thomas
India Nelson
Peggy Joyce
Bruce Kruse
Magali Woods
James Mertz
Anastasia Mederios
Marty Pendleton
Lee Caudill
Lois Thompson
Christopher Conder
Gerald Meil
Joseph Manley
Antonio Jimenez
Caroline Boatner
Lynn Asakura
Linda Hubbell
Kathleen Ausdemore
Patricia Bryan
Alexander Vincent
Ruth Mckneely
Paul Canfield
Louis Laney
Jack Sievers
Angie Mcconnell
Armando Ragsdale
Dale Immediato
Matthew Holmes
John Perkins
Charles Mays
Ardella Biagioni
Jacqueline Marshall
Boyd Mchattie
Roger Howard
Lyndon Wagner
Timothy Craig
Nga Hodge
Gary Webster
James Alberts
Jose Reed
Steven Jones
Jason Brown
Marcus Figueroa
Calvin Drelick
Mary Bentley
Donald Boyce
Elizabeth Albright
Kent Traverso
James Adams
Nelda Thomson
Pamela Puglia
Tracy Williams
Larry Harrington
Daniel Carrillo
Russell Williams
Dianne Lester
Kenneth Franklin
Betsy Martin
Sondra Bolton
Robert Ellington
Ebony Wolf
Jake Cowart
Ray Chandler
Jack Huether
Hector Ellinger
Adele Coltrain
Justin Zanes
David Gibson
Caleb Sweeney
Prince Bell
Helen Hudley
Andrea Jimenez
Christie Puffinburger
Donald Love
Joyce Bona
Megan Chalmers
Cyril Payne
Florence Cooper
Albert Burnett
Molly Boyd
Steve Rapp
Derek Rivera
Zora Heath
Gene Hughes
Michael Bush
Carol Raymer
Rodney Sheaffer
Kenneth Griffin
Lorena Noyes
Charles Cureton
Daniel Adelstein
Manuel Moreland
Yvonne Stallcup
Donna Barr
Bruce Crider
Tina Chrisman
Alene Inman
Richard Hargrove
Daniel Lacuesta
Lila Lorna
Carl Heinlein
Jean Vann
Barbara Perez
Michelle Barbour
Tiffany Otis
Charlotte Davis
Virgen Asquith
Rebecca Rodriguez
Evelyn Ferreira
Darrell Esterly
Keith Garza
Dean Wallace
Mary Oconnor
Lynn Naone
Evelyn Chaney
Robert Wright
David Spicer
Celia Williams
Sean Betterman
Paul Medlock
David Pare
Salvatore Guthrie
Anna Witzke
Tom Nunley
Kathyrn Choi
Samantha Springer
Derrick Hawley
Maybell Robinson
Steven Harris
Lois Ruth
David Williams
Susann Perez
Linda Clouse
Lawanda Mcnutt
Frances Dalton
Ricky Jones
Jose Tamborlane
Marvin Wallace
Martha Werner
Maureen Garibay
Laura Ledet
David Teixeira
Richard Core
Claudine Marley
Adele Hillebrandt
Jerry Conner
Rose Reilly
Norman Williams
Kenneth Riebau
Joseph Mcdaniel
Catherine Burnett
Karen Antilla
Dee Rothfuss
Elsie Wells
Jennifer Cowan
Linda Mckoy
Josette Nutter
Jennifer Devore
Lori Owen
Michael Crawford
Steven Stovall
Ervin Schuster
Manuela Cleveland
Allan Rooks
Kristine Gonzalez
Mary Sutton
Melinda Chaney
John Morrone
Marilyn Reyna
Scott Ryan
Geoffrey Carr
Judith Reinsch
Henry Weatherby
Brian Rush
Joshua Ernst
Nicholas Wanzer
Evelyn Asquith
Shela Blew
Matthew Wilson
Krista Phan
Joshua Groch
Amanda Kelly
Charles Folsom
Johnathan Bambeck
Rhonda Bruder
Erin Oakman
Thelma Patrick
Melinda Abbott
Michael Myers
Betty Hamlin
Joanne White
Irene Alvarez
Gerry Walter
David Johnston
Dexter Sherrer
Joseph Bustos
Susan Prater
William Mickel
Carlos Chipps
Alice Redmond
Bruce Rohr
Norma Borek
Bruno Bunch
Bessie Green
Mike Imes
John Davis
David Brunson
Sharon Parker
Daryl Carroll
Mary Diaz
Thomas Mcconnell
Jessica Jones
Jane Barnard
Rodney Middleton
Wallace Conti
Harriet Croshaw
Ruben Deloach
Gary Jeffries
Mike Cashio
Elizabeth Shelly
Virginia Herring
Martha Bradford
Timothy Byrum
Peter Arms
Jose Tanner
Evelyn Morton
Jannie Ceraos
Christa Melanson
Reynaldo Beier
Mari Kirksey
Adam Wiley
Isidro Foster
Matthew Green
Mary Morales
Linda Mcgeorge
Marsha Collins
Christina Anderson
Jimmy Ostrander
Lessie Baker
Elizabeth Echols
Lisa Zepeda
Michael Raynor
Heather Johnson
Margaret Ayala
Holly Dubinsky
Kami Zamora
Douglas House
James Parrish
Russell Acuna
Michael Aguirre
Susan Morales
Peter Meeks
Reva Smith
Marjorie Webb
Marcos Long
Joanne Cothren
Juanita Lazo
David Boyd
Latoya Clayton
Louie Meadows
Mark Winstead
Lois Thompson
Stephen Fisher
Israel Eastman
Cynthia Tomlinson
Marsha Yaney
David Ellis
Victor Edmonds
Michael Griffiths
Theodore Hernandez
Eric Curry
Gladys Evans
Jan Moody
David Connolly
Adrienne Dalton
Kay Crawford
Peter Santiago
Anthony Nice
Brenda Zhu
Benjamin Shah
Frank Mcintosh
Lee Kellam
Santos Tucker
Lillie Campos
Lillian Hart
Thersa Nopper
Rosa Baker
Willie Mccabe
Michael Caraballo
Summer Feldman
Justin Gaspard
Denise Tippetts
Judith Schmid
Charles Pankey
Cheryl Davis
Sandra Turner
Jason Eisele
Charles Chapman
Margaret Saucier
Brian Shanks
Crystal Rohn
Ebony Vincent
Brooke Carrell
Elaine Petersen
Opal Boles
Elvis James
Hermelinda Brown
Amanda Paul
Mary Zimmerman
Adam Roth
Samuel Carroll
Lorena Hamilton
Ruby Fisher
Winifred Adams
Jose Yancey
Pearl Vaughn
Novella Mckinney
Jesica Watts
Retta Yates
Christie Marotta
Lisa Lowrance
Melissa Hudley
Megan Kjelland
Josephine Mcneal
Dianne Jobe
Rose Morgan
Robert Pitt
Jennifer Blackman
Lizbeth Para
Elton Crum
Derek Griffith
Julia Pengelly
Barry Powell
Michael Simpson
Diana Bluma
Jesus Lebeau
Walter Coates
Alma Smith
Libby Tyner
Ronald Holt
Mark Murray
James Love
George Ellis
Julia Fenstermacher
Harry Schroder
Jeremy Hernandez
Wayne Creason
Joe Gulbranson
Nicole Miller
Willene Windham
Todd South
Edwin Proctor
David Parlin
John Wilson
Kathryn Warwick
Ola Zavala
Charles Belmont
Brent Riddell
Helen Bassett
Hubert Amos
Sarah Deangelo
Kyle Lindsay
Wendell Martin
Gayle Higa
Kenneth Fowler
Alissa Hamberg
Junior Dodd
Gail Stockman
Wendell Zook
Damion Skeans
Dennis Nation
Sharon Enriquez
Robert Cole
Robert Mckay
Andrea Gainey
David Cervantes
Joanne Simmons
Arnold Free
Dorothy Woods
Vera Burnett
Sharon Hazelton
Paula Dewoody
Shari Hagee
Donald Bruder
Mattie Cortez
Max Richardson
Jose Deleon
Mary Mauldin
Eugene Deutsch
Julie Bartley
Christina Stender
Elma Whipps
Cheryl Perez
Jose Heatherington
Christopher Calaf
Dixie Quintana
Rosemary Novotny
Bradley Gonzales
Jessie Ward
Brian Gibson
Sarah Humphrey
Linda Mccracken
Larry Orr
Lauren Rodrigues
Eric Jackson
Tilda Mcduffie
William Johnson
Julie Kronenberg
Jeanette Sandlin
Nancy Zediker
Edward Richter

In [5]:
#---Read the type, shape, & size of dataset---#

#---Read the type of dataset---#
print('The type of the dataset is:', type(names))

#---Read the shape of dataset---#
print('The shape of the dataset is:', np.shape(names))

#---Read the size of dataset---#
print('The size of the dataset is:', np.size(names))

#---Read the length of dataset---#
print('The length of the dataset is:', len(names))

The type of the dataset is: <class 'str'>
The shape of the dataset is: ()
The size of the dataset is: 1
The length of the dataset is: 14024

In [6]:
#---Split the names into a list---#
names = names.strip().split('\n')
print(names[0:10])
print('The length of the dataset is:', len(names))

['Edward Davis', 'John Brown', 'Cristopher Mccrate', 'Michael Combes', 'Jeff Blount', 'Joseph Ferris', 'Pablo Bruner', 'Ronnie Waite', 'Edward Gonzalez', 'Ruby Musetti']
The length of the dataset is: 1000

In [7]:
#---Password Generator---#
sp_symbols = ['!', '@', '#', '$', '&', '?']
def pass_generator():

    pwd = []
    caps_alpha = [chr(random.randrange(65, 65 + 26)) for _ in range(random.randrange(1, 4))]
    small_alpha = [chr(random.randrange(97, 97 + 26)) for _ in range(random.randrange(3, 6))]
    np.random.shuffle(sp_symbols)
    pwd.append(sp_symbols[0])
    num = [str(random.randrange(1, 10)) for _ in range(random.randrange(1, 4))]
    pwd = num + caps_alpha + small_alpha + pwd
    np.random.shuffle(pwd)
    pwd = ''.join(pwd)
    return pwd

In [8]:
pass_generator()

'P91typ1c&'

In [9]:
#---Email ID Generator---#
def email_id(name):
    name = name.split()
    email = '.'.join(name)
    return email.lower() + '@edureka.co'

In [10]:
print(email_id('Edward Davis'))

edward.davis@edureka.co

In [11]:
emp_id = [id for id in range(2020001, 2020001 + 1000)]
email_id = [email_id(name) for name in (names)]
password = [pass_generator() for _ in range(1000)]

In [12]:
print(emp_id[:10])
print(email_id[:10])
print(password[:10])

[2020001, 2020002, 2020003, 2020004, 2020005, 2020006, 2020007, 2020008, 2020009, 2020010]
['edward.davis@edureka.co', 'john.brown@edureka.co', 'cristopher.mccrate@edureka.co', 'michael.combes@edureka.co', 'jeff.blount@edureka.co', 'joseph.ferris@edureka.co', 'pablo.bruner@edureka.co', 'ronnie.waite@edureka.co', 'edward.gonzalez@edureka.co', 'ruby.musetti@edureka.co']
['Rkb8r1#', 'Ug8s$CslpL', 'v?b6EwjiY', 'z7el9I5d&u', '6&K1i6lfvG', 'wr5@h91Hk', 'n5!33Boa', 'ILi?Qi4qf', 'fkQ6yr@VI', 'cw8lgUYb&R']

# ***Task 2.***

> Developing a DataFrame.

In [ ]:
#---Checking the length of the lists before creating the DataFrame to check for consistency---#
print("Names:", len(names))
print("Employee ID:", len(emp_id))
print("Email ID:", len(email_id))
print("Password:", len(password))

Names: 1000
Employee ID: 1000
Email ID: 1000
Password: 1000

In [ ]:
#---Creating a DataFrame with names, email IDs, and passwords---#
df = pd.DataFrame({"Names": names, "Employee ID": emp_id, "Email ID": email_id, "Password": password})

# ***Task 3.***
> Just to cross-check, showing the first  and the last  rows. Also, checking the shape, null values of the DataFrame and print the data-types of each column.

In [ ]:
#---Displaying the first 10 rows of the DataFrame---#
print(df.head(10))

                Names  Employee ID                       Email ID    Password
0        Edward Davis      2020001        edward.davis@edureka.co     Rkb8r1#
1          John Brown      2020002          john.brown@edureka.co  Ug8s$CslpL
2  Cristopher Mccrate      2020003  cristopher.mccrate@edureka.co   v?b6EwjiY
3      Michael Combes      2020004      michael.combes@edureka.co  z7el9I5d&u
4         Jeff Blount      2020005         jeff.blount@edureka.co  6&K1i6lfvG
5       Joseph Ferris      2020006       joseph.ferris@edureka.co   wr5@h91Hk
6        Pablo Bruner      2020007        pablo.bruner@edureka.co    n5!33Boa
7        Ronnie Waite      2020008        ronnie.waite@edureka.co   ILi?Qi4qf
8     Edward Gonzalez      2020009     edward.gonzalez@edureka.co   fkQ6yr@VI
9        Ruby Musetti      2020010        ruby.musetti@edureka.co  cw8lgUYb&R

In [ ]:
#---Displaying the last 10 rows of the DataFrame---#
print(df.tail(10))

                Names  Employee ID                     Email ID     Password
990   Linda Mccracken      2020991   linda.mccracken@edureka.co     kd&Cl948
991         Larry Orr      2020992         larry.orr@edureka.co   @Gfo1Yn8hY
992  Lauren Rodrigues      2020993  lauren.rodrigues@edureka.co   49&f7hHbRs
993      Eric Jackson      2020994      eric.jackson@edureka.co    baz62Qy!8
994    Tilda Mcduffie      2020995    tilda.mcduffie@edureka.co     4Fwxdac!
995   William Johnson      2020996   william.johnson@edureka.co  8vrDpt61#OP
996  Julie Kronenberg      2020997  julie.kronenberg@edureka.co   mgL9Tjt!De
997  Jeanette Sandlin      2020998  jeanette.sandlin@edureka.co     xmOY#e6v
998     Nancy Zediker      2020999     nancy.zediker@edureka.co    mZh7?wCnT
999    Edward Richter      2021000    edward.richter@edureka.co  &p1q7R8bKzv

In [17]:
#---Displaying the shape of the DataFrame---#
nRaw, nCol = df.shape
print(f'There are {nRaw} raws and {nCol} columns:')

#---Displaying the size of the DataFrame---#
print('The size of the DataFrame is:', df.size)

#---Displaying the type of the DataFrame---#
print('The type of the DataFrame is:', type(df))

There are 1000 raws and 4 columns:
The size of the DataFrame is: 4000
The type of the DataFrame is: <class 'pandas.DataFrame'>

In [ ]:
#---Displaying null values in the DataFrame---#

null = df.isnull()
if null is True:
    print('There are null values in the DataFrame.')
else:
    print('There are no null values in the DataFrame.')

print(null.sum())

There are no null values in the DataFrame.
Names          0
Employee ID    0
Email ID       0
Password       0
dtype: int64

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Names        1000 non-null   str
 1   Employee ID  1000 non-null   int64
 2   Email ID     1000 non-null   str
 3   Password     1000 non-null   str
dtypes: int64(1), str(3)
memory usage: 31.4 KB

# ***Task 4.***
> 4. Print the employee id, email id, and password of ‘Nancy Zediker’.

In [30]:
#---Display the employee id, email id, and password of ‘Nancy Zediker’---#
print(df[df['Names'] == 'Nancy Zediker'])

             Names  Employee ID                  Email ID   Password
998  Nancy Zediker      2020999  nancy.zediker@edureka.co  mZh7?wCnT

# ***Task 5.*** 

>    5.a Check the column ‘Email ID’.

>    5.b Check it should not contain any duplicate emails.

>    5.c Check its size and print the first 10 values.

>    5.d Check if duplicate email is found, add a number in the duplicated email.

In [ ]:
#---Display the email IDs of all employees---#
email_series = df['Email ID']
print(email_series)

0            edward.davis@edureka.co
1              john.brown@edureka.co
2      cristopher.mccrate@edureka.co
3          michael.combes@edureka.co
4             jeff.blount@edureka.co
                   ...
995       william.johnson@edureka.co
996      julie.kronenberg@edureka.co
997      jeanette.sandlin@edureka.co
998         nancy.zediker@edureka.co
999        edward.richter@edureka.co
Name: Email ID, Length: 1000, dtype: str

In [48]:
print('The size of Email ID is....', email_series.size)
print('Type of Email ID is....', type(email_series))

The size of Email ID is.... 1000
Type of Email ID is.... <class 'pandas.Series'>

In [47]:
print(email_series.info())

<class 'pandas.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: Email ID
Non-Null Count  Dtype
--------------  -----
1000 non-null   str
dtypes: str(1)
memory usage: 7.9 KB
None

In [37]:
#---Checking duplicate values in the DataFrame---#
duplicate = df['Email ID'].duplicated()
print(duplicate)
print('The total number of duplicate values in the DataFrame is:', duplicate.sum())

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Email ID, Length: 1000, dtype: bool
The total number of duplicate values in the DataFrame is: 1

In [39]:
df[df['Email ID'].duplicated()]

             Names  Employee ID                  Email ID  Password
850  Lois Thompson      2020851  lois.thompson@edureka.co  KL4ou7$e

In [40]:
df[df['Names'] == 'Lois Thompson']

             Names  Employee ID                  Email ID    Password
598  Lois Thompson      2020599  lois.thompson@edureka.co  5ro$f2aG1x
850  Lois Thompson      2020851  lois.thompson@edureka.co    KL4ou7$e

In [ ]:
#---Adding a Number in duplicate Email iD---#
df.loc[850, 'Email ID'] = 'lois.thompson1@edureka.co'

In [ ]:
print(df.loc[850])

Names                      Lois Thompson
Employee ID                      2020851
Email ID       lois.thompson1@edureka.co
Password                        KL4ou7$e
Name: 850, dtype: object

In [44]:
df[df['Names'] == 'Lois Thompson']

             Names  Employee ID                   Email ID    Password
598  Lois Thompson      2020599   lois.thompson@edureka.co  5ro$f2aG1x
850  Lois Thompson      2020851  lois.thompson1@edureka.co    KL4ou7$e

# ***Task 6.***
> Creating the first batch of all people whose names are starting with ‘A’. Also give me their count.

In [59]:
start_a = df[df['Names'].str.startswith('A')]
print(start_a)

              Names  Employee ID                   Email ID    Password
23       Alfredo Yu      2020024      alfredo.yu@edureka.co  revD9BU4#f
68   Ashley Nettles      2020069  ashley.nettles@edureka.co     xG&gs5R
77     Alice Vallee      2020078    alice.vallee@edureka.co   X6j@pm69p
96   Adrienne Huber      2020097  adrienne.huber@edureka.co    5Nbx3f3?
113     Ahmad Olson      2020114     ahmad.olson@edureka.co    7zwg&YXM
..              ...          ...                        ...         ...
898       Adam Roth      2020899       adam.roth@edureka.co  Ycq22G?vjm
926      Alma Smith      2020927      alma.smith@edureka.co   hdi$752gB
954  Alissa Hamberg      2020955  alissa.hamberg@edureka.co   s$Wg11kuW
963   Andrea Gainey      2020964   andrea.gainey@edureka.co  N@f5Lh3fsv
966     Arnold Free      2020967     arnold.free@edureka.co   mciD98A&u

[62 rows x 4 columns]

In [63]:
print(start_a.count())

Names          62
Employee ID    62
Email ID       62
Password       62
dtype: int64

In [62]:
print(start_a.shape)

(62, 4)

In [52]:
print(start_a.info())

<class 'pandas.DataFrame'>
Index: 62 entries, 23 to 966
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Names        62 non-null     str
 1   Employee ID  62 non-null     int64
 2   Email ID     62 non-null     str
 3   Password     62 non-null     str
dtypes: int64(1), str(3)
memory usage: 2.4 KB
None

# ***Task 7.***
> People at index 10, 130, and 560 will not be joining so remove their record.

In [ ]:
print(df.loc[[10, 130, 560]])

              Names  Employee ID                   Email ID   Password
10      Della Janek      2020011     della.janek@edureka.co    b6a&sLM
130  William Ponyah      2020131  william.ponyah@edureka.co    wi8$Huw
560  Joseph Brussel      2020561  joseph.brussel@edureka.co  99vy2!Lvq

In [69]:
#---Dropping the peoples who will not join the company---#
df.drop([10, 130, 560], inplace = True)

In [70]:
print(df.info())

<class 'pandas.DataFrame'>
Index: 997 entries, 0 to 999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Names        997 non-null    str
 1   Employee ID  997 non-null    int64
 2   Email ID     997 non-null    str
 3   Password     997 non-null    str
dtypes: int64(1), str(3)
memory usage: 38.9 KB
None

In [72]:
print(df.head())

                Names  Employee ID                       Email ID    Password
0        Edward Davis      2020001        edward.davis@edureka.co     Rkb8r1#
1          John Brown      2020002          john.brown@edureka.co  Ug8s$CslpL
2  Cristopher Mccrate      2020003  cristopher.mccrate@edureka.co   v?b6EwjiY
3      Michael Combes      2020004      michael.combes@edureka.co  z7el9I5d&u
4         Jeff Blount      2020005         jeff.blount@edureka.co  6&K1i6lfvG

In [73]:
print(df.tail())

                Names  Employee ID                     Email ID     Password
995   William Johnson      2020996   william.johnson@edureka.co  8vrDpt61#OP
996  Julie Kronenberg      2020997  julie.kronenberg@edureka.co   mgL9Tjt!De
997  Jeanette Sandlin      2020998  jeanette.sandlin@edureka.co     xmOY#e6v
998     Nancy Zediker      2020999     nancy.zediker@edureka.co    mZh7?wCnT
999    Edward Richter      2021000    edward.richter@edureka.co  &p1q7R8bKzv

# ***Task 8.***
> Creating a new DataFrame without the password column and save it in an excel file for sharing.

In [77]:
new_df_without_pass = df.drop('Password', axis=1)
if 'Password' not in new_df_without_pass.columns:
    print("Password column is dropped successfully.")

Password column is dropped successfully.

In [78]:
print(new_df_without_pass.info())

<class 'pandas.DataFrame'>
Index: 997 entries, 0 to 999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Names        997 non-null    str
 1   Employee ID  997 non-null    int64
 2   Email ID     997 non-null    str
dtypes: int64(1), str(2)
memory usage: 31.2 KB
None

# ***Task 9.***
> Displaying how can access the data from excel file using names. For example show me the data for 'John Brown’ and 'Michael Combes’.

In [83]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in C:\Users\ravis\AppData\Roaming\Python\Python314\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\ravis\AppData\Roaming\Python\Python314\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [84]:
new_df_without_pass.to_excel("data_without_pass.xlsx", index = False)
df.to_excel('org_dataset.xlsx', index = False)

In [86]:
check = pd.read_excel('data_without_pass.xlsx')

In [87]:
print(check.head())

                Names  Employee ID                       Email ID
0        Edward Davis      2020001        edward.davis@edureka.co
1          John Brown      2020002          john.brown@edureka.co
2  Cristopher Mccrate      2020003  cristopher.mccrate@edureka.co
3      Michael Combes      2020004      michael.combes@edureka.co
4         Jeff Blount      2020005         jeff.blount@edureka.co

In [96]:
print(check.loc[check['Names'] == 'John Brown'])

        Names  Employee ID               Email ID
1  John Brown      2020002  john.brown@edureka.co

In [97]:
print(check[check['Names'] == 'John Brown'])

        Names  Employee ID               Email ID
1  John Brown      2020002  john.brown@edureka.co

In [ ]:
#---Loading the dataset---#
!wget https://www.dropbox.com/s/onl5ac2ea3v11aw/names.txt

'wget' is not recognized as an internal or external command,
operable program or batch file.

# ***###-----Thank you-----###***